<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseWPF>true</UseWPF>

		<Version>1.1.0</Version>
		<AssemblyVersion>1.1.0.0</AssemblyVersion>
		<FileVersion>1.1.0.0</FileVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="closeprogrambutton.png" />
      <None Remove="hidewindowbutton.png" />
      <None Remove="mainWindowBG.png" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    </ItemGroup>

    <ItemGroup>
      <Resource Include="closeprogrambutton.png" />
      <Resource Include="hidewindowbutton.png" />
      <Resource Include="mainWindowBG.png" />
    </ItemGroup>

</Project>
